Nigeria refactor
owid/covid-19-data pull request #2110
Opened 2021-11-04 21:59 UTC by camappel

Feel free to contribute at #2099

2021-11-08 12:50 UTC, lucasrodes requested changes

2021-11-08 12:50 UTC, lucasrodes commented on scripts/scripts/testing/automations/incremental/nigeria.py
> +    soup = BeautifulSoup(req.content, "html.parser")
You can try to use `cowidev` library here:

```python
soup = get_soup(source_url)
```

Note that for this to work you need to import `get_soup` function at the top of the script as:

```python
from cowidev.utils.web import get_soup
```

2021-11-08 12:50 UTC, lucasrodes commented on scripts/scripts/testing/automations/incremental/nigeria.py
> +    data = pd.read_csv("automated_sheets/Nigeria.csv").sort_values(by="Date", ascending=False)
To ensure the path works regardless of where the script is executed, I'd suggest using function `get_project_dir` as:

```python
path = os.path.join(get_project_dir(), "scripts", "scripts", "testing", "automated_sheets", "Nigeria.csv")
data = pd.read_csv(path).sort_values(by="Date", ascending=False)
```

Note you need to import:

```python
import os
from cowidev.utils.utils import get_project_dir
```

2021-11-08 12:50 UTC, lucasrodes commented on scripts/scripts/testing/automations/incremental/nigeria.py
> +        df.to_csv("automated_sheets/Nigeria.csv", index=False)
Use

```python
df.to_csv(path, index=False)
```

2021-11-10 15:37 UTC, camappel reviewed
Thank you for incorporating the cowidev library

2021-11-10 19:15 UTC, lucasrodes requested changes

2021-11-10 19:17 UTC, lucasrodes requested changes

2021-11-10 19:17 UTC, lucasrodes commented on scripts/scripts/testing/automations/incremental/nigeria.py
> +    cumulative_total = int(soup.find("div", class_="col-xl-3").find("span").text.replace(",", ""))
Use [clean_count()](https://github.com/owid/covid-19-data/blob/a3a100d280ecbf0e5da0c654b4d09fae067da0a3/scripts/src/cowidev/utils/clean/numbers.py#L88)

```python
from cowidev.utils.clean import clean_count
element = soup.find("div", class_="col-xl-3").find("span")
cumulative_total = clean_count(element.text)
```

2021-11-11 19:41 UTC, merged