data(tests,usa): calculate positivate
owid/covid-19-data pull request #2335
Opened 2022-01-26 15:18 UTC by camappel

Improvement on #2334

2022-01-26 16:55 UTC, edomt requested changes
Thanks - is there a reason behind the `.fillna("")` on line 54?
Also there seems to be an issue with the general structure: some parts are functions and some other parts are methods inside `UnitedStates` - @lucasrodes can help with sorting this out if needed.

2022-01-27 21:16 UTC, camappel commented
Thanks for pointing this out. I was using the structure that was already implemented, but I'm happy to fix it

2022-01-28 12:59 UTC, lucasrodes approved these changes
LGTM!

Added some minor styling changes.

2022-01-28 13:05 UTC, edomt approved these changes

2022-01-28 13:05 UTC, merged